version: 2
jobs:
  shellcheck:
    docker:
      - image: nlknguyen/alpine-shellcheck:v0.4.6
    steps:
      - checkout
      - run:
          name: Check scripts
          command: |
            shellcheck --external-sources check_new_release
            shellcheck --external-sources vke_brew_commit
  build-job:
    docker:
      - image: circleci/ubuntu-server:latest
    steps:
      - add_ssh_keys:
        fingerprints:
          - "01:fb:47:4a:a7:b4:cb:1b:c7:41:34:08:4d:d8:67:3a"
      - run:
          name: Update completion script based on this commit
          command: |

            git clone git@github.com:ali5ter/vke-completion.git

            popd vke-completion >/dev/null || exit 1

            ./create_completion

            if [[ $(git status -s | grep -c 'M vke_bash_completion.sh') == 1 ]]; then
                git add vke_bash_completion.sh && \
                git commit -m'Update completion for new CLI build' && \
                git push
            fi

            popd >/dev/null || exit 1

workflows:
  version: 3
  workflow:
    jobs:
      - shellcheck
      - build-job:
          requires:
            - shellcheck
          filters:
            branches:
              only: master
