version: 2
jobs:
  shellcheck:
    docker:
      - image: nlknguyen/alpine-shellcheck:v0.4.6
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: |
            shellcheck --external-sources check_new_release
  build-job:
    docker:
      - image: circleci/ubuntu-server:latest
    steps:
      - checkout
      - run:
          name: Update tap if new VKE CLI available
          command: |
            echo 'Mon, 10 Sep 2018 22:37:39 GMT' > .last_release
            ./check_new_release

workflows:
  version: 2
  workflow:
    jobs:
      - shellcheck
      - build-job:
          requires:
            - shellcheck
          filters:
            branches:
              only: master