version: 2
jobs:
  shellcheck:
    docker:
      - image: nlknguyen/alpine-shellcheck:v0.4.6
    steps:
      - checkout
      - run:
          name: Check scripts
          command: |
            shellcheck --external-sources check_new_release
            shellcheck --external-sources vke_brew_commit
  build_completion_script:
    docker:
      - image: circleci/ubuntu-server:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "70:c3:03:6b:0e:e0:31:cc:a1:dd:e5:3c:de:24:8c:05"
      - run:
          name: Install and configure git
          command: |
            apt update -y
            apt install git -y
            git config --global user.email "alister@lewis-bowen.org"
            git config --global user.name "Alister Lewis-Bowen"
      - run:
          name: Create completion script and commit if there are changes
          command: |
            git clone git@github.com:ali5ter/vke-completion.git
            popd vke-completion >/dev/null || exit 1
            ./create_completion
            if [[ $(git status -s | grep -c 'M vke_bash_completion.sh') == 1 ]]; then
                git add vke_bash_completion.sh && \
                git commit -m'Update completion for new CLI build' && \
                git push
            fi
            popd >/dev/null || exit 1

workflows:
  version: 2
  workflow:
    jobs:
      - shellcheck
      - build_completion_script:
          requires:
            - shellcheck
          filters:
            branches:
              only: master
