version: 2
jobs:
  shellcheck:
    docker:
      - image: nlknguyen/alpine-shellcheck:v0.4.6
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: |
            shellcheck --external-sources check_new_release
  build-job:
    docker:
      - image: circleci/ubuntu-server:latest
    steps:
      - checkout
      - run:
          name: Update tap if new VKE CLI available
          command: |
            set -x
            API_BASE='https://circleci.com/api/v1.1'
            API_PROJECT="$API_BASE/project/github/ali5ter/homebrew-vke-cli"
            LAST_BUILD=$(CIRCLE_BUILD_NUM - 2)
            API_ARTIFACTS="$API_PROJECT/$LAST_BUILD/artifacts"
            URL_LAST_RELEASE=$(curl -s -u $CIRCLE_TOKEN: "$API_ARTIFACTS" | grep url | grep .last_release | cut -d'"' -f4)
            curl -s "$URL_LAST_RELEASE" -o .last_release
            ./check_new_release
      - store_artifacts:
          path: .last_release

workflows:
  version: 2
  workflow:
    jobs:
      - shellcheck
      - build-job:
          requires:
            - shellcheck
          filters:
            branches:
              only: master