version: 2
jobs:
  shellcheck:
    docker:
      - image: nlknguyen/alpine-shellcheck:v0.4.6
    steps:
      - checkout
      - run:
          name: Check scripts
          command: |
            shellcheck --external-sources check_new_release
            shellcheck --external-sources vke_brew_commit
  build_completion_script:
    docker:
      - image: circleci/python:2.7
    steps:
      - run:
          name: Clone completion script repo
          working_directory: ${CIRCLE_WORKING_DIRECTORY}
          command: |
            git clone https://${GITHUB_PERSONAL_TOKEN}@github.com/ali5ter/vke-completion.git
      - deploy:
          name: Create completion script and commit if there are changes
          working_directory: ${CIRCLE_WORKING_DIRECTORY}/vke-completion
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "alister@lewis-bowen.org"
            git config user.name "CircleCI deployment job"
            ./create_completion
            if [[ $(git status -s | grep -c 'M vke_bash_completion.sh') == 1 ]]; then
                git add vke_bash_completion.sh && \
                git commit -m'Update completion for new CLI build' && \
                git push
                git push -q https://${GITHUB_PERSONAL_TOKEN}@github.com/ali5ter/vke-completion.git master
            fi

workflows:
  version: 2
  workflow:
    jobs:
      - shellcheck
      - build_completion_script:
          requires:
            - shellcheck
          filters:
            branches:
              only: master
