version: 2
jobs:
  shellcheck:
    docker:
      - image: nlknguyen/alpine-shellcheck:v0.4.6
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: |
            shellcheck --external-sources check_new_release
  build-job:
    docker:
      - image: circleci/ubuntu-server:latest
    steps:
      - checkout
      - run:
          name: Update tap if new VKE CLI available
          command: |

            FILE='.last_build_date'
            ## TODO: Need a reliable way to determin the last build
            BUILD=$((CIRCLE_BUILD_NUM - 2))
            API_BASE='https://circleci.com/api/v1.1/project/github/ali5ter/homebrew-vke-cli'
            API_ARTIFACTS="$API_PROJECT/$BUILD/artifacts"

            echo "Fetching $FILE from build $BUILD"
            ARTIFACTS=$(curl -s -u $CIRCLE_TOKEN: "$API_ARTIFACTS" | grep url || echo '')
            if [[ ! -z "$ARTIFACTS" ]]; then
              LAST_RELEASE=$(grep "$FILE" "$ARTIFACTS" || echo '')
              if [[ ! -z "$LAST_RELEASE" ]]; then
                URL_LAST_RELEASE=$(echo "$LAST_RELEASE" | cut -d'"' -f4)
                curl -s "$URL_LAST_RELEASE" -o "$FILE"
                echo "Found $FILE containing date $(cat $FILE)"
              else
                echo "  No artifacts named $FILE found in build $BUILD"
              fi
            else
              echo "  No artifacts found in build $BUILD"
            fi

            echo "Check for new VKE CLI build and update brew tap"
            ./check_new_release

      - store_artifacts:
          path: .last_build_date

workflows:
  version: 2
  workflow:
    jobs:
      - shellcheck
      - build-job:
          requires:
            - shellcheck
          filters:
            branches:
              only: master
